### ISSUE TITLE
not able to configure ALB with kong GW proxy 

### ISSUE THREAD

**Issue by jalawala** [aws-samples/terraform-eks-blueprints-kong-samples#10]
@DaniellaFreese  @anshrma  I see TG health checks (to 8000/HTTP at path /) fail when I create ingress to create ALB in front of Kong GW pods. I want to use ALB to enable WAF.  Can it work with HTTP or do we need to use HTTPS as mandate? Please share any working config. 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kong
  name: kong-gateway-proxy5 
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    #alb.ingress.kubernetes.io/healthcheck-port: "8000"
    #alb.ingress.kubernetes.io/healthcheck-path: /                                  
    #alb.ingress.kubernetes.io/healthcheck-protocol: HTTP  
    alb.ingress.kubernetes.io/healthcheck-port: kong-proxy
    alb.ingress.kubernetes.io/load-balancer-name: kong-gateway-proxy-alb 
    alb.ingress.kubernetes.io/scheme: internet-facing 
    alb.ingress.kubernetes.io/target-type: ip # 
    #alb.ingress.kubernetes.io/target-type: instance 
spec:
  ingressClassName: alb 
  rules:
  - http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: kong-gateway-proxy 
            port:
              number: 80 
```
