### ISSUE TITLE
Konnect + KIC + EKS Fargate -> Internal NLB being created

### ISSUE THREAD

**Issue by htims1989** [aws-samples/terraform-eks-blueprints-kong-samples#14]
I'm trying to merge two of the examples, that is I want to use KIC with Konnect and the EKS Cluster to use Fargate.

I'm close, but the NLB that is being assigned to the `kong-gateway-proxy` service is internal. I believe I need to set an annotation:
`service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"` but I'm struggling to figure out how to do it.

In order to get the gateway pods up and running I needed to set `resources` otherwise they would be assigned the Fargate minimums and not start up. I had to do that by providing `kong_values.yaml` as follows:
```
#-------------------------------------------------------------------------------
# Kong parameters
# -----------------------------------------------------------------------------
gateway:
  resources:
    limits:
      cpu: 1200m
      memory: 800Mi
    requests:
      cpu: 300m
      memory: 300Mi
```

I'm not sure how I figured out it needed to be set in `gateway` but thats the only thing that works. I was hoping I could then just amend that to:
```
#-------------------------------------------------------------------------------
# Kong parameters
# -----------------------------------------------------------------------------
gateway:
  enabled: true
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Type=proxy"
    external-dns.alpha.kubernetes.io/hostname: "proxy.kong-dp.internal"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

  resources:
    limits:
      cpu: 1200m
      memory: 800Mi
    requests:
      cpu: 300m
      memory: 300Mi
```

But that doesn't take affect, the service doesn't have the annotations applied and I end up with an internal NLB. I've also tried setting it within `proxy` instead of `gateway` but that doesn't work either.

How do I get an external NLB using KIC + Fargate? Someone has asked a similar question here without a reply:
https://discuss.konghq.com/t/kong-ingress-controller-with-internet-facing-nlb-aws-eks/11889

**Comment by htims1989** [comment]
Of course once I ask the question, I figure it out:
```
#-------------------------------------------------------------------------------
# Kong parameters
# -----------------------------------------------------------------------------

gateway:
  resources:
    limits:
      cpu: 1200m
      memory: 800Mi
    requests:
      cpu: 300m
      memory: 300Mi
  proxy:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Type=proxy"
      external-dns.alpha.kubernetes.io/hostname: "proxy.kong-dp.internal"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
```
